import { getImageUrl } from '../lib/images';

export type PhotoTag = 'Landscape' | 'Cityscape' | 'Street' | 'Car';

export interface PhotoExif {
  camera?: string;
  lens?: string;
  focalLength?: string;
  aperture?: string;
  shutterSpeed?: string;
  iso?: string;
  dateTaken?: string;
  width?: number;
  height?: number;
}

export interface PhotoMetadata {
  id: string;
  r2Path: string;
  title: string;
  location: string;
  tags: PhotoTag[];
  isHero: boolean;
  order?: number;
  exif: PhotoExif;
}

// Auto-generated by `npm run sync-photos` — committed to repo
import registryRaw from './photo-registry.json';
// Hand-curated metadata — edit photo-meta.json to add titles, locations, tags, hero status
import photoMetaRaw from './photo-meta.json';

type RegistryEntry = {
  camera?: string | null;
  lens?: string | null;
  focalLength?: string | null;
  aperture?: string | null;
  shutterSpeed?: string | null;
  iso?: string | null;
  dateTaken?: string | null;
  width?: number | null;
  height?: number | null;
  error?: string;
};

type PhotoMetaEntry = {
  title?: string;
  location?: string;
  tags?: PhotoTag[];
  isHero?: boolean;
  order?: number;
  width?: number;
  height?: number;
};

const registry = registryRaw as Record<string, RegistryEntry>;
const photoMeta = photoMetaRaw as Record<string, PhotoMetaEntry>;

function pathToId(r2Path: string): string {
  return r2Path
    .replace(/\.[^.]+$/, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function defaultTitle(r2Path: string): string {
  const filename = r2Path.split('/').pop() || r2Path;
  return filename.replace(/\.[^.]+$/, '').replace(/_/g, ' ');
}

// Maps photo ID to R2 path
export const imageSources: Record<string, string> = {};

export const photos: PhotoMetadata[] = Object.entries(registry)
  .filter(([, entry]) => !entry.error)
  .map(([r2Path, exifData]) => {
    const id = pathToId(r2Path);
    const meta = photoMeta[r2Path];
    imageSources[id] = r2Path;
    return {
      id,
      r2Path,
      title: meta?.title || defaultTitle(r2Path),
      location: meta?.location || '',
      tags: meta?.tags || [],
      isHero: meta?.isHero || false,
      order: meta?.order,
      exif: {
        camera: exifData.camera ?? undefined,
        lens: exifData.lens ?? undefined,
        focalLength: exifData.focalLength ?? undefined,
        aperture: exifData.aperture ?? undefined,
        shutterSpeed: exifData.shutterSpeed ?? undefined,
        iso: exifData.iso ?? undefined,
        dateTaken: exifData.dateTaken ?? undefined,
        width: exifData.width ?? meta?.width ?? undefined,
        height: exifData.height ?? meta?.height ?? undefined,
      },
    };
  });

export type PhotoId = string;

export function getHeroPhotos(): PhotoMetadata[] {
  return photos
    .filter(photo => photo.isHero)
    .sort((a, b) => {
      const orderA = a.order ?? Infinity;
      const orderB = b.order ?? Infinity;
      return orderA - orderB;
    });
}

export function getPhotosByTag(tag: PhotoTag): PhotoMetadata[] {
  return photos.filter(photo => photo.tags.includes(tag));
}

export function getPhotoById(id: string): PhotoMetadata | undefined {
  return photos.find(photo => photo.id === id);
}

export function getImageSource(id: PhotoId): string | undefined {
  return imageSources[id];
}

export function getImageSourceUrl(id: PhotoId): string | undefined {
  const r2Path = imageSources[id];
  return r2Path ? getImageUrl(r2Path) : undefined;
}

export const allTags: PhotoTag[] = ['Landscape', 'Cityscape', 'Street', 'Car'];

export const tagBannerPhotos: Record<PhotoTag | 'all', string> = {
  'all': '2025_Chicago/DSC_4517.jpg',
  'Landscape': '2025-12-20_Hawaii-Trip/DSC_8535.jpg',
  'Cityscape': '2025_Chicago/DSC_4517.jpg',
  'Street': '2025-12-20_Hawaii-Trip/DSC_9035.jpg',
  'Car': '2025-12-20_Hawaii-Trip/DSC_9068.jpg',
};

export function getBannerPhotoForTag(tag: PhotoTag | 'all'): string {
  return tagBannerPhotos[tag];
}

export function getBannerImageUrl(tag: PhotoTag | 'all'): string {
  return getImageUrl(getBannerPhotoForTag(tag));
}

export function getPhotosSortedByDate(): PhotoMetadata[] {
  return [...photos].sort((a, b) => {
    const dateA = a.exif.dateTaken ? new Date(a.exif.dateTaken).getTime() : 0;
    const dateB = b.exif.dateTaken ? new Date(b.exif.dateTaken).getTime() : 0;
    return dateB - dateA;
  });
}
